/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mycompany;

public class App {

    public static void main(String[] args) {

        StateMachine sm = new StateMachine();
        while(true) {
            sm.run();
        }

    }
}
